import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header";
import Navbar from "./components/shared/Navbar";
import Marquee from "./components/shared/Marquee";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Bangla News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // data-theme="dark"
      // data-theme="light"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased theme-dark`}  //full black
      className={`${notoSerifBengali} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Header></Header>
        <Navbar></Navbar>
        <Marquee></Marquee>
        <main className="flex-1 max-w-7xl mx-auto">
          {children}
        </main>

      </body>
    </html>
  );
}
